controller_joint_names: ['Rotor_R_joint_name', 'Hel_R_joint_name', 'Rotor_L_joint_name', 'Hel_L_joint_name', 'Rudder_R_joint_name', 'Rudder_L_joint_name', 'Aileron_R_joint_name', 'Aileron_L_joint_name', ]
